### ISSUE TITLE
The "install" command should update the lock file

### ISSUE THREAD

**Issue by vovimayhem** [uranusjr/pipfile-cli#1]
When running `pipfile install` on an updated `Pipfile` (by adding a new package), I was expecting `pipfile-cli` to install the new packages and update the `Pipfile.lock` contents.

Instead, I got the following error:

```
Your Pipfile.lock (c0e2495760bc67926e1078615eb142c55c96690b3ab0729c123048e799e616e8) is out of date. Expected: (d69e08d1c80d74d5bc15b4caa31c059f06ff5b9858fab2b7b10b258f65789227). Aborting
```

IMHO the behavior should be to always update the lock file with the new packages, pretty much like other dependency managers do, such as Yarn & bundler.

I'm opening the discussion here to prevent me doing some code without actually discussing this first :)

**Comment by uranusjr** [comment]
Hmm. This is actually a conscious design decision: I want to make the locking phase as explicit as possible. Using [Sam Boyer’s approach](https://medium.com/@sdboyer/so-you-want-to-write-a-package-manager-4ae9c17d9527#3d9e), there are essentially three things we want to do when using a lock file-based dependency management tool: (I’ll use Pipfile and Pipfile.lock to make things easier to understand)

* `f(P→M)` modifies Pipfile, adding and/or removing dependencies you want for the project.
* `f(M→L)` modifies Pipfile.lock. Basically what `pipenv lock` does.
* `f(L→D)` sets up your environment based on Pipfile.lock. Basically `pipenv sync`, or `pipenv install --ignore-pipfile`.

I really like the cleanness and explicitness of this approach, and plan to stick out to see how far it can take us. `pipfile install` is `f(L→D)`, which means it does not care about locking (it does check to make sure your lock file is valid, but that can be skipped with `--no-check`).

Maybe what I really should do is to avoid the word “install” because people tend to expect things from that verb. I guess `lock` and `sync` from Pipenv are reasonable (the latter is used by Boyer as well).

Note: `lock` is currently not implemented at all, but it should in the future. For now, unfortunately, I can only recommend using Pipenv to lock, and Pipfile-CLI to deploy. Also I don’t plan to ever implement `f(P→M)`. I believe in hand-writing Pipfile.

(I’m keeping this issue open as a todo item for myself.)

**Comment by vovimayhem** [comment]
Interesting reading - it's the first time I see project dep management so intricately explained (this guy has to have some sort of OCD... I like that!)

While I feel `f(P→M)` is a nice thing to have (like `bundle install foo` or `yarn add bar`), I see how they are not as important (not a priority at all) as `f(M→L)`. I'm totally OK editing the manifest directly.

So, let's say it's actually `lock` the operation I'm looking for... which is not yet implemented:

* I'm understanding that the `lock` command should stop after dumping the dep tree to the lock file, is it correct? If so, what would it be the (real) use or value of having the project's deps not in sync with the lock file?
* Given the `f(M→L)` might be the scary part, do you have any ideas/plan about how to implement it? (maybe bringing some code from pipenv may or may not work?)

**Comment by uranusjr** [comment]
1. There is not, IMO. Conceptually the environment should always be in sync with the lock file. There are implementation advantages to separate the two steps, however, because locking is (theoretically) a “pure” operation, while installing has intrinsic side effects to your environment. Separating them into two steps makes it much easier to design and test the functionalities in isolation, and allows the user to recover more easily from an error.
2. My plan is to reuse/share Pipenv’s resolver. It is quite separate from the rest of Pipenv, and is a good candidate to be extracted as a standalone library. The ideal result is to share most of the logic with Pipenv (we already do in `pipfile` and `requirementslib`), but to expose the functionalities differently, and without the involvement of virtualenv.
